import React from 'react'
import { AiOutlinePieChart } from 'react-icons/ai'
import { FaEnvelopeOpenText } from 'react-icons/fa'
import { FaMapSigns } from 'react-icons/fa'
import { FaWpforms } from 'react-icons/fa'
import { AiFillReconciliation } from 'react-icons/ai'
function Agriculture() {
  return (
    <>
      <div className="about-container">
        <div className="container-content">
          <h1 className="deficrypto">Application of Blockchain Agriculture</h1>
          <p className="tm-para">
            <b>Overview</b>
            <br />
            One of the biggest challenges that this sector faces is tracking and
            paying for the delivery of food. Both sellers and buyers have agents
            that increase the size of the chain, making the product more
            expensive than its original value and is time-consuming.
            <br />
            With the existence of blockchain technology, this problem can be
            resolved easily. Since there would be a single distributed ledger,
            the communication between the buyer and seller would improve,
            meaning, there would be a decrease in the number of agents. With
            features like traceability and suitability, farmers can directly
            contact restaurants or individual buyers and can get a larger share
            for their sales. It will also remove the exploitation done by
            intermediaries to both parties.
          </p>
        </div>
      </div>
      <div className="team-container">
        <div className="team-container-content">
          <br /> <br />
          <h4 className="cf-software">
            Blockchain technology can drive in profits for the industry
          </h4>
          <p className="bitcoin-para">
            The gaming industry is not new to the blockchain technology but it
            is still at its elementary stage. There are various kinds of games
            built on the blockchain technology which are earning a good deal
            amount in the current market. CryptoKitties is the most famous and
            demanded game on the blockchain network. CryptoKitties is an
            authentic game which allows players to purchase, breed and deal in
            digital kittens with the help of cryptocurrency. The game was
            launched in October 2017 and only after three months, it earned a
            profit of US$12 million. The full version of the game wasn't kept
            live for more than a week.
          </p>
          <p className="bitcoin-para">
            In the blockchain technology, game developers are not the only
            person who can take advantage of the system. The players can also
            earn profits. The game CryptoKitties allowed players to encash their
            tokens by selling their kittens to other players. Once the number of
            kittens doubled in number the players can sell those to other
            players. Games such as this give away a place for the players to
            make money as well. Developers do not have the right to produce
            virtual money. Non-fungible tokens are authentic in its own nature.
            It is next to impossible to make an image of such tokens because
            they possess a unique address on the blockchain network.
          </p>
        </div>
      </div>
      <div className="advantages container">
        <h3 className="advantage">How will this system work?</h3>
        <div className="hyper">
          <p className="lending">
            Data Generation The data will be generated by three major categories
            Crop and soil monitoring: Temperature, pH level of soil,pesticides
            and water spray from IoT sensors and weather and wind monitoring
            data. Warehousing and distribution: Quality control, tracking
            transportation and food safety control. Retail and marketing: Bill
            data, taxes and compliance.
          </p>

          <p className="lending">
            Data Processing This data will be processed in form of smart
            contracts to keep the chain transparent to investors.
          </p>

          <p className="lending">
            Blockchain Consumptions This data will be hashed and saved on
            blockchains. Information on land usage, crop efficiency, financial
            audit and flood mitigation can be collected from these chains.
          </p>
        </div>
      </div>

      <div className="container-bottom">
        <div className="bottom-left">
          <h6 className="www">Why work with us !</h6>
          <br />
          <h3 className="dnw">Does your bussiness need a website ?</h3>
          <br />
          <h2 className="left-text">We're available</h2>
          <br />
          <p className="left-para">
            If you want to expand your business in the digital domain and need
            an affordable solution, we are here to help you by building a
            cost-effective yet professional website design for a near-perfect
            start of the digital journey for your products and services. Get in
            touch with us, we’d love to hear your idea and give your business
            “DIGITAL WINGS”.
          </p>
          <br />
          <button className="wa">
            <i className="fab fa-telegram"></i> Telegram
          </button>
        </div>

        <div className="bottom-right">
          <h5 className="right-text-1">
            <AiOutlinePieChart size={30} /> Affordable Pricing
          </h5>
          <br />
          <p className="right-para-1">
            Kesavi Web Solutions is the most affordable WordPress website
            designing agency based in South Delhi, India. We offer the most
            cost-effective services depending on the specific requirements of
            each project and budget. Our services fit well in small pockets.
          </p>
          <h5 className="right-text 2">
            <i className="fas fa-thumbs-up"></i> Professional Design
          </h5>
          <br />
          <p className="right-para-2">
            Every project we work upon is a new challenge for us to create a new
            masterpiece. It is also an opportunity to know about the client’s
            ideas, values, and mission, audience, brand values, competition.
            This helps us shape the UI/UX accordingly and create a rich user
            experience with a professional design. <br />
            Kesavi Web Solutions strives to create a personalized website design
            that is in harmony with the ideas of the business.
          </p>
        </div>
      </div>
      <div className="footer-container">
        <div className="footer-text-wrappers">
          <div className="footer-text-items">
            <div className="footer text item-1">
              <h4>REGD.OFFICE</h4>
              <h6 className="bnd">
                {' '}
                <i className="fas fa-map-marker-alt fa-2x"></i> Badarpur, New
                Delhi,
                <br /> India 110044
              </h6>
              <h6>
                {' '}
                <i className="fas fa-phone fa-2x"></i> (+) 91 - 9717453904
              </h6>
              <h6>
                {' '}
                <FaEnvelopeOpenText size={30} className="fa" />{' '}
                info@kesaviweb.com
              </h6>
            </div>

            <div className="footer-text-item-2">
              <h4>FOR ROBOTS</h4>
              <h6>
                {' '}
                <FaWpforms size={30} className="fas" /> Privacy Policy
              </h6>
              <h6>
                {' '}
                <AiFillReconciliation size={30} className="ai" /> Terms &
                Conditions
              </h6>
              <h6>
                {' '}
                <FaMapSigns size={30} className="fa" /> Site Map
              </h6>
            </div>

            <div className="footer-text-item-3">
              <h4>FOR HUMANS</h4>
              <h6>Home</h6>
              <h6>Portfolio</h6>
              <h6>Free Online Quote</h6>
              <h6>Website Cost Estimation</h6>
            </div>

            <div className="footer-text-item-4">
              <img className="src " src="images/KWS_6693.png" alt="logo img" />
              <h6 className="ncr">
                Most Affordable Website Designing Company based in South Delhi,
                NCR, India.
              </h6>

              <h6 className="company">
                Built with ❤ <b>By K.W.S</b>
              </h6>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Agriculture
